DROP TABLE IF EXISTS "OrderItem";
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS "Dish";
DROP TABLE IF EXISTS "Categories";
DROP TABLE IF EXISTS "Address";
DROP TABLE IF EXISTS "User";

DROP EXTENSION IF EXISTS "pgcrypto";
