version: "3.8"

services:
  # 1. Postgres Database
  db:
    image: postgres:17
    container_name: restaurant_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Migrations Service
  migrations:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: restaurant_migrations
    restart: on-failure
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # 3. My Go Application
  online-restaurant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_restaurant_app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrations
    command: ["/online-restaurant"]  # or whatever your binary is named
