services:
  online-restaurant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=development
      - LOG_FORMAT=text
      - LOG_SEVERITY=debug