name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: restaurant_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'

    # Backend checks
    - name: Go format check
      run: gofmt -s -w . && git diff --exit-code

    - name: Go vet
      run: go vet ./...

    - name: Go tests
      env:
        POSTGRES_DB: restaurant_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_PORT: 5432
      run: go test ./...

    - name: Go build
      run: go build -o bin/app ./backend
